### ISSUE TITLE
Karpenter v0.32 doesn't work without having pre v0.32 crds installed inside the cluster

### ISSUE THREAD

**Issue by samuel-esp** [aws/karpenter-core#792] opened 2023-11-16 10:39 UTC
### Description

**Observed Behavior**:

Hi everyone, I just noticed a strange behavior during the installation phase. Today I installed Karpenter v0.32 on a clean cluster and noticed that the Karpenter pods can't start if old CRDs are not currently installed inside the cluster (AWSNodeTemplate, Provisioner, Machine) as well as new CRDs (ec2nodeclass, nodepools, nodeclaims).

```
karpenter-6f76b66487-dlj6t   0/1     CrashLoopBackOff   5 (88s ago)   4m32s
karpenter-6f76b66487-kw58t   0/1     CrashLoopBackOff   5 (80s ago)   4m32s
```

doing kubectl logs inside the Karpenter pod i get this error

```
{"level":"DEBUG","time":"2023-11-16T07:50:36.555Z","logger":"controller","message":"loaded log configuration from file \"/etc/karpenter/logging/zap-logger-config\"","commit":"1072d3b"}
{"level":"DEBUG","time":"2023-11-16T07:50:36.555Z","logger":"controller","message":"discovered karpenter version","commit":"1072d3b","version":"v0.32.1"}
panic: failed to setup machine provider id indexer: failed to get API group resources: unable to retrieve the complete list of server APIs: karpenter.sh/v1alpha5: the server could not find the requested resource
 
goroutine 1 [running]:
github.com/samber/lo.must({0x25adc00, 0xc0000a53a0}, {0xc000a0f730, 0x1, 0x1})
        github.com/samber/lo@v1.38.1/errors.go:51 +0x1c5
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.38.1/errors.go:72
github.com/aws/karpenter-core/pkg/operator.NewOperator()
        github.com/aws/karpenter-core@v0.32.1/pkg/operator/operator.go:182 +0x16ce
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:33 +0x25
```

In particular the problem seems related to some v1alpha

`panic: failed to setup machine provider id indexer: failed to get API group resources: unable to retrieve the complete list of server APIs: karpenter.sh/v1alpha5: the server could not find the requested resource`

Does Karpenter main loop search for something related to v1alpha even after a clean installation? 

To fix this problem I installed (as well) v0.31 CRDs (aws-node-templates, provisioner, machine) and did a rollout restart of Karpenter deploy. It magically solved the problem. Tried as well to replicate the issue uninstalling the old CRDs and rollout restarting Karpenter deploy and it failed again. So the problem seems related to old CRDs missing inside the Cluster

_Note_: if you are upgrading from 0.31 you shouldn't notice this behavior unless you uninstalled old CRDs from the Cluster at some point

**Expected Behavior**:

I should be able to install Karpenter without Old CRDs being present inside the Cluster. Apprently, right now, Karpenter wants both Old and New CRDs at the same time

**Reproduction Steps** (Please include YAML):

Followed the main installation guide. installed the Karpenter Infra Cloudformation and the helm chart below (parameters inside the helm template were correctly injected)

**Versions**:
- Chart Version: karpenter oci://public.ecr.aws/karpenter/karpenter --version 0.32.1
- Kubernetes Version (`kubectl version`): 1.25

**Comment by samuel-esp** [comment] 2023-11-16 10:41
#659 it seems to report the same problem

**Comment by jonathan-innis** [comment] 2023-11-17 19:46
> Does Karpenter main loop search for something related to v1alpha even after a clean installation

We have to have a version of Karpenter that supports both the old alpha CRDs and the new CRDs in order to support a migration path for users that are coming from older versions of Karpenter. 

We are currently working on Karpenter v0.33.0 which should drop the need to have the alpha versions and _only_ support beta.

**Comment by jonathan-innis** [comment] 2023-11-17 19:47
I'm going to close this since this appears to be a duplicate of #659

**Closed by jonathan-innis** 2023-11-17 19:47 UTC
Labels: bug

**Comment by aafaq-rashid-comprinno** [comment] 2023-11-19 20:37
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version ${KARPENTER_VERSION} --namespace karpenter --create-namespace \
  --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"="arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterControllerRole-${CLUSTER_NAME}" \
  --set settings.clusterName=${CLUSTER_NAME} \
  --set settings.interruptionQueue=${CLUSTER_NAME} \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait

**Comment by jonathan-innis** [comment] 2023-11-21 17:37
> without crds

The setup that you are referring to _will_ install the CRDs; notably, it makes sure that all the CRDs are there when the install occurs. I think the key point here is that for the v0.32.x minor version, you need both the alpha APIs and the beta APIs for Karpenter to run. This will no longer be true starting on minor version v0.33.x
