### ISSUE TITLE
support custom device plugin resource

### ISSUE THREAD

**Issue by lzjqsdd** [aws/karpenter-core#308] opened 2023-04-28 10:01 UTC
### Tell us about your request

'Provision' CRD support custom device plugin resource which  can be ignored when matching ec2 instances

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

in my case,  pod need mount /dev/fuse.   Now we build a device plugin for /dev/fuse,  and register `example/fuse` resource to kubelet,  and already deploy a daemonSet for this resource.  this case is same like “nvidia.com/gpu” .   But  karpenter can't identify "example/fuse",   and won't privisioning new k8s node.

if karpenter can ignore this custom resource ,and still provisioning new node ,  the "example/fuse" daemonSet will depoly soon, and pod can be scheduled immediately.

so, i think if karpenter `Provisioner`  CRD can support custom device plugin resource, and ignore this resource when trying to match available ec2 instances.

### Are you currently working around this issue?

Now i have to create a leading pod without this "example/fuse" resource.   And force karpenter to provisioning new node.  Then delete this leading pod when it's running, this means i already got enough resource for real pod.   And the real pod which need "example/fuse" can be scheduled soon. this solution seems some kind of weird . 

So If karpetner native support custom device plugin resource woluld be best,  users just define custom Provisioner  for his needed resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment] 2023-05-01 16:53
Linking the relevant issues that are tracking similar requests"
1. https://github.com/aws/karpenter/issues/3376
2. https://github.com/aws/karpenter/issues/1900
3. https://github.com/aws/karpenter/issues/3315

**Comment by jonathan-innis** [comment] 2023-05-01 21:38
Closing this as a duplicate of https://github.com/aws/karpenter/issues/1900. Do you mind adding your use-case to that larger issue?

**Closed by jonathan-innis** 2023-05-01 21:38 UTC
Labels: needs-design, feature

**Comment by lzjqsdd** [comment] 2023-05-04 01:38
> Closing this as a duplicate of [aws/karpenter#1900](https://github.com/aws/karpenter/issues/1900). Do you mind adding your use-case to that larger issue?

ok
