### ISSUE TITLE
Karpenter cannot replace fault EKS node automatically

### ISSUE THREAD

**Issue by yumengok** [aws/karpenter-core#328] opened 2023-05-08 21:49 UTC
### Version

__Karpenter Version:__ v0.27.1

__Kubernetes Version:__ 1.23

### Expected Behavior

There was underlying hardware issue happened yesterday and impacted one of EKS nodes managed by Karpenter.

When I checked today, this EKS node showed "NotReady" state. At that time, I could not ssh / ping / SSM to that EC2 instance.
The only pod running on that node showed "Terminating" state.

This hardware issue happened yesterday. And "NotReady" + "Terminating" state have lasted for more than 10 hours.

This "NotReady" state was resolved by deleting node with kubectl command. Karpenter was able to take care of rest steps like provisioning new node.

Expect an automatically way to heal itself from underlying hardware issue.

### What will ASG(Auto Scaling Group) do?
With same interruption in above reproduce section, ASG removed that problem EC2 instance and provisioned a new one.

### Actual Behavior

This "NotReady" state was resolved by deleting node with kubectl command. After that Karpenter was able to take care of rest steps like provisioning new node.

### Steps to Reproduce the Problem

Manually ssh/SSM to one healthy EKS node and execute "ifdown eth0" to simulate a node network outage.
Above "NotReady" and "Terminating" situation can be reproduced. 
This issue is able to be resolved until one of below manual step is engaged:

1. kubectl delete node <node name>
2. Terminate this EC2 instance (problem node) from AWS UI

### Resource Specs and Logs

`apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  ...
spec:
  consolidation:
    enabled: true
  kubeletConfiguration:
    podsPerCore: 2
  labels:
    ...
  limits:
    resources:
      cpu: 1k
      memory: 4Ti
  providerRef:
    name: default
  requirements:
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - c
    - m
    - r
  - key: karpenter.k8s.aws/instance-cpu
    operator: In
    values:
    - "8"
    - "16"
    - "32"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: karpenter.k8s.aws/instance-size
    operator: NotIn
    values:
    - nano
    - micro
    - small
    - medium
    - large
...`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by yumengok** [comment] 2023-05-08 22:55
My concern is:
If one AWS AZ is down and causing EC2 instances "half dead", like EC2 instances are running, but network is disconnect etc.
The Karpenter will not able to remove those EKS nodes in that problem AZ, and then provision new nodes to replace them.

**Comment by jonathan-innis** [comment] 2023-05-08 23:31
This looks like a duplicate of https://github.com/aws/karpenter/issues/2021. Would you mind adding additional info to that issue so that we keep all the related information in once place? I'm going to close this as a dupe for now.

**Closed by jonathan-innis** 2023-05-08 23:31 UTC
Labels: bug
